name: Build
on:
  pull_request:
  push:
jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'front-end/.node-version'
      - name: Install dependencies
        working-directory: ./front-end
        run: npm ci
      - name: Build vite application
        working-directory: ./front-end
        run: npm run build
